version: "3"
services:
  weihua:
    image: weihua
    volumes:
      - ./pb_data:/app/pb_data
    restart: always
    network_mode: host
  yolo:
    image: yolo
    restart: always
    network_mode: host
    volumes:
      - ./venv:/opt/venv
