name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: backend/pocketbase
        run: docker build . --file Dockerfile --tag weihua:latest

      - name:
          Install ssh keys
          # check this thread to understand why its needed:
          # <https://stackoverflow.com/a/70447517>
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.M }}" > ~/.ssh/id_rsa
          ssh-keyscan -H junction.nyman.dev > ~/.ssh/known_hosts

      - name: Copy image to server
        run: docker save weihua:latest | bzip2 | ssh root@junction.nyman.dev "docker load && cd backend && docker compose up -d"
